name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize node & npm
        uses: actions/checkout@v4 

      - name: Execute Cypress Tests
        uses: cypress-io/github-action@v6

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            cypress/reports/
