name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Latest stable

      - name: Use Node.js
        uses: actions/setup-node@v4  # Latest stable
        with:
          node-version: 'node'  # Uses the latest LTS version of Node.js

      - name: Install dependencies
        run: npm ci

      - name: Start server
        run: npm start &
        env:
          CI: true

      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@v2  # v2 is the latest stable version
        with:
          url: 'http://localhost:3000'
          timeout: '60'

      - name: Run Cypress tests
        run: npx cypress run
